[workspace]
members = ["client", "server", "shared"]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.14.0" }
bevy_quinnet = { version = "0.9.0" }
avian3d = { version = "0.1.1" }
serde = { version = "1.0", features = ["derive"] }
